version: "3"
services:
  GeneratedProjectName:
    build:
        context: .\
        dockerfile: Dockerfile
    ports:
        - "11111:11111"
        - "30000:30000"
        - "8080:8080"
        - "5000:80"