name: CI Build

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Install dependencies for C# solution
      run: dotnet restore orleans-template-dev-csharp.sln
    - name: Build C# solution
      run: dotnet build --configuration Release --no-restore orleans-template-dev-csharp.sln
    - name: Test C# solution
      run: dotnet test --no-restore --verbosity normal orleans-template-dev-csharp.sln
    - name: Install dependencies for F# solution
      run: dotnet restore orleans-template-dev-fsharp.sln
    - name: Build F# solution
      run: dotnet build --configuration Release --no-restore orleans-template-dev-fsharp.sln
    - name: Test F# solution
      run: dotnet test --no-restore --verbosity normal orleans-template-dev-fsharp.sln
 
