name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish UniversalSilo
      uses: johnazariah/publish-nuget@master
      with:
        PROJECT_FILE_PATH: universal-silo/universal-silo.fsproj
        NUGET_KEY:    ${{secrets.NUGET_API_KEY}}
        PACKAGE_NAME: Orleans.Contrib.UniversalSilo
    - name: Publish Templates
      uses: johnazariah/publish-nuget@master
      with:
        PROJECT_FILE_PATH: template-pack/Orleans.Contrib.UniversalSilo.Templates.csproj
        NUGET_KEY:    ${{secrets.NUGET_API_KEY}}
        PACKAGE_NAME: Orleans.Contrib.UniversalSilo.Templates

