name: Build & Push UniversalSilo Templates Package
on:
  push:
    tags:
      - 'tpl*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build, Pack and Push Templates
      run: make LibraryVersion=${GITHUB_REF##*/tpl} push-template-pack
