name: CI

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
    tags-ignore:
      - lib*
      - tpl*

jobs:
  build-and-test-solutions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: build-and-test-solutions
      run: make build
    - name: build-template-pack
      run: make copy-template-pack pack-template-pack
    - name: upload-template-pack
      uses: actions/upload-artifact@v2
      with:
        name: template-pack
        path: Orleans.Contrib.UniversalSilo.Templates.*.nupkg
  verify-templates:
    needs: build-and-test-solutions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [csharp, fsharp]
        template: [webapi, silo, client, silo-and-client]
      fail-fast: false
      max-parallel: 8
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: download-template-pack
      uses: actions/download-artifact@v2
      with:
        name: template-pack
    - name: install-template-pack
      run: make install-template-pack
    - name: verify-templates
      run: make test-template.${{ matrix.template }}.${{ matrix.lang }}
